### ISSUE TITLE
feathers-plus generate app crashing

### ISSUE THREAD

**Issue by eddyystop** [feathers-plus/generator-feathers-plus#121]
https://github.com/feathersjs/generator-feathers/issues/394

Anthoni Gardner <notifications@github.com>
I am getting an error what I try and do an install of the app.
node version : 10/13.0
npm version: 6.4.1
linux mint version : Linux Mint 18.3 (Sylvia)

events.js:167
      throw er; // Unhandled 'error' event
      ^

TypeError: Cannot read property 'test:all' of undefined
    at app (/home/anthoni/.nvm/versions/node/v10.13.0/lib/node_modules/@feathers-plus/cli/node_modules/@feathers-plus/generator-feathers-plus/generators/writing/index.js:341:42)
    at generatorWriting (/home/anthoni/.nvm/versions/node/v10.13.0/lib/node_modules/@feathers-plus/cli/node_modules/@feathers-plus/generator-feathers-plus/generators/writing/index.js:266:7)
    at AppGenerator.writing (/home/anthoni/.nvm/versions/node/v10.13.0/lib/node_modules/@feathers-plus/cli/node_modules/@feathers-plus/generator-feathers-plus/generators/app/index.js:187:5)
    at Object.<anonymous> (/home/anthoni/.nvm/versions/node/v10.13.0/lib/node_modules/@feathers-plus/cli/node_modules/yeoman-generator/lib/index.js:424:27)
    at /home/anthoni/.nvm/versions/node/v10.13.0/lib/node_modules/@feathers-plus/cli/node_modules/run-async/index.js:25:25
    at new Promise (<anonymous>)
    at /home/anthoni/.nvm/versions/node/v10.13.0/lib/node_modules/@feathers-plus/cli/node_modules/run-async/index.js:24:19
    at self.env.runLoop.add.completed (/home/anthoni/.nvm/versions/node/v10.13.0/lib/node_modules/@feathers-plus/cli/node_modules/yeoman-generator/lib/index.js:425:13)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
Emitted 'error' event at:
    at Immediate.setImmediate (/home/anthoni/.nvm/versions/node/v10.13.0/lib/node_modules/@feathers-plus/cli/node_modules/yeoman-generator/lib/index.js:433:22)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)

**Comment by eddyystop** [comment]
The error results from package.json not have a scripts prop. I don't see how that can happen if you ran `generate app` in an empty folder.

1. Could you please mention all the steps you took between creating an empty folder and running `generate app`.

2. Please post the feathers-gen-specs.json file from the folder.

Thanks.

**Comment by franfran3** [comment]
I had the same issue:
```
mkdir test
cd test
yarn init -y
yarn add @feathers-plus/cli
node ./node_modules/.bin/feathers-plus g app
```
Validate choices with default (except package manager as yarn):
```
We are creating a new app in dir test
? Project name test
? Description Project test
? What folder should the source files live in? src
? Which package manager are you using
  (has to be installed globally)? Yarn
? What type of API are you making?
 REST, Realtime via Socket.io
? Data mutating tests and seeding may run when NODE_ENV is one of (optional) 
events.js:167
      throw er; // Unhandled 'error' event
      ^

TypeError: Cannot read property 'test:all' of undefined
    at app (/tmp/test/node_modules/@feathers-plus/generator-feathers-plus/generators/writing/index.js:341:42)
    at generatorWriting (/tmp/test/node_modules/@feathers-plus/generator-feathers-plus/generators/writing/index.js:266:7)
    at AppGenerator.writing (/tmp/test/node_modules/@feathers-plus/generator-feathers-plus/generators/app/index.js:187:5)
    at Object.<anonymous> (/tmp/test/node_modules/yeoman-generator/lib/index.js:424:27)
    at /tmp/test/node_modules/run-async/index.js:25:25
    at new Promise (<anonymous>)
    at /tmp/test/node_modules/run-async/index.js:24:19
    at self.env.runLoop.add.completed (/tmp/test/node_modules/yeoman-generator/lib/index.js:425:13)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
Emitted 'error' event at:
    at Immediate.setImmediate (/tmp/test/node_modules/yeoman-generator/lib/index.js:433:22)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
```

I edited package.json and added: 
```
"scripts": {
    "test:all": "/bin/true"
}
```
then regenerate the app.

**Comment by franfran3** [comment]
Yes the above was from a brand new directory.
I could not install globaly on the machine because of a lack of privileges, but I don't think that the problem is on that point.
IMO "test:all" is a script added  by @feathersjs/feathers, so this package should be installed *before* @feathers-plus/cli. Maybe that point should be highlighted in the doc.
Another solution would be to call @feathersjs/feathers post-install scripts if the package was not installed.

**Comment by eddyystop** [comment]
In your https://github.com/feathers-plus/generator-feathers-plus/issues/162 you mention you created a package.json before running generate app. That is not allow, as I state above in https://github.com/feathers-plus/generator-feathers-plus/issues/121#issuecomment-442285405 . The generator expects a empty folder when you run generate app for the first time.

**Comment by eddyystop** [comment]
I think I can close this issue since a lack of reply would indicate the last response addressed the issue.
