### ISSUE TITLE
mysql adapter template missing

### ISSUE THREAD

**Issue by Flippo24** [feathers-plus/generator-feathers-plus#62]
When runing 'feathers-plus generate service' i got an file missing error for mysql.ejs adapter.

Using generator version 0.6.37

? What is the name of the service? users...gen service name validate. input= users
...updating service

? What is the name of the service? users
? What would you call one row in the users database? user
? What kind of service is it? Sequelize
? Place service code in which nested folder, e.g. `v1/blog`? (optional)
? Which path should the service be registered on? /users
? Should this be served by GraphQL? Yes
     skip src\services\users\users.class.js
     skip src\services\users\users.interface.js
     skip src\app.interface.ts
     skip src\typings.d.ts
? Which database are you connecting to? MySQL (MariaDB)
? What is the database connection string? mysql://root:@localhost:3306/feathers_graphql
     skip src\typings.d.ts
events.js:183
      throw er; // Unhandled 'error' event
      ^

AssertionError [ERR_ASSERTION]: Trying to copy from a source that does not exist: C:\Users\xyz\AppData\Roaming\npm\node_modules\@feathers-plus\cli\node_modules\@feathers-plus\generator-feathers-plus\generators\writing\templates\src\_adapters\mysql.ejs
    at EditionInterface.exports.copy (C:\Users\xyz\AppData\Roaming\npm\node_modules\@feathers-plus\cli\node_modules\mem-fs-editor\lib\actions\copy.js:48:3)
    at EditionInterface.module.exports [as copyTpl] (C:\Users\xyz\AppData\Roaming\npm\node_modules\@feathers-plus\cli\node_modules\mem-fs-editor\lib\actions\copy-tpl.js:29:8)
    at todos.forEach (C:\Users\xyz\AppData\Roaming\npm\node_modules\@feathers-plus\cli\node_modules\@feathers-plus\generator-feathers-plus\lib\generator-fs.js:48:24)
    at Array.forEach (<anonymous>)
    at generatorFs (C:\Users\xyz\AppData\Roaming\npm\node_modules\@feathers-plus\cli\node_modules\@feathers-plus\generator-feathers-plus\lib\generator-fs.js:26:9)
    at connection (C:\Users\xyz\AppData\Roaming\npm\node_modules\@feathers-plus\cli\node_modules\@feathers-plus\generator-feathers-plus\generators\writing\index.js:848:5)
    at generatorWriting (C:\Users\xyz\AppData\Roaming\npm\node_modules\@feathers-plus\cli\node_modules\@feathers-plus\generator-feathers-plus\generators\writing\index.js:274:7)
    at ConnectionGenerator.writing (C:\Users\xyz\AppData\Roaming\npm\node_modules\@feathers-plus\cli\node_modules\@feathers-plus\generator-feathers-plus\generators\connection\index.js:176:5)
    at Object.<anonymous> (C:\Users\xyz\AppData\Roaming\npm\node_modules\@feathers-plus\cli\node_modules\yeoman-generator\lib\index.js:424:27)
    at C:\Users\xyz\AppData\Roaming\npm\node_modules\@feathers-plus\cli\node_modules\run-async\index.js:25:25
    at new Promise (<anonymous>)
    at C:\Users\xyz\AppData\Roaming\npm\node_modules\@feathers-plus\cli\node_modules\run-async\index.js:24:19
    at self.env.runLoop.add.completed (C:\Users\xyz\AppData\Roaming\npm\node_modules\@feathers-plus\cli\node_modules\yeoman-generator\lib\index.js:425:13)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)

**Comment by eddyystop** [comment]
Thanks for this awkward catch!

I want to let you know I've been checking all the DBs and all the adapters.

**Comment by eddyystop** [comment]
The previous commit allowed the tests to call multiple generates rather than just doing a "generate all". That broke "generate connection" when called by "generate service".

All 34 adapter/Db combinations were checked for both f+/cli and f/cli. They need to be rechecked.

A test is needed for each to ensure this doesn't break again.

**Comment by eddyystop** [comment]
Fix published in f+/cli v0.7.39 which runs generator v0.6.38 .

@Flippo24  please confirm it resolves your issue. Thanks.

**Comment by Flippo24** [comment]
Now it's working as expected. 
Thanks for your work.

**Comment by eddyystop** [comment]
26 tests were added to cover the adapter/database combinations f+/cli handles.

Published in f+/cli v0.7.40 which runs generator v0.6.39
